KDIR := /lib/modules/5.13.0-7620-generic/build 
PWD := $(shell pwd)
obj-m := camdriver.o
camdriver-y := take_picture.o
camdriver-y += uart_help.o
camdriver-y += uart/uart.o


all:
	make -C $(KDIR) M=$(PWD) modules
clean:
	make -C $(KDIR) M=$(PWD) clean
